<option value="Accueil">Accueil / Service d'ordre</option>
<option value="Compassion">Actes de compassion</option>
<option value="Prophetique">Action prophétique</option>
<option value="Communication">Communication</option>
<option value="Decoration">Décoration</option>
<option value="Delivrance">Délivrance</option>
<option value="direction_campagne">Direction de campagne</option>
<option value="Discipline">Discipline</option>
<option value="EnfanceDeVie">Enfance de vie</option>
<option value="Evangelisation">Evangélisation plein air porte à porte</option>
<option value="EventManager">Event manager</option>
<option value="FlammesDeVie">Flammes de vie</option>
<option value="Healing">Healing team</option>
<option value="Intendance">Intendance</option>
<option value="Intercession">Intercession</option>
<option value="Logistique">Logistique</option>
<option value="MedecineDeVie">Médecine de vie</option>
<option value="Protocole">Protocole</option>
<option value="Sono">Régie technique</option>
<option value="Restauration">Restauration</option>
<option value="RestaurationLeaman">Restauration Leaman</option>
<option value="Securite">Sécurité</option>
<option value="SmalahEnAction">Smalah en mission</option>
<option value="Boutique">Sociales (boutique 931)</option>
<option value="Temoignage">Témoignage de vie</option>
<option value="Temoins">Témoins et conseillers</option>
<option value="Transport">Transport</option>